#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib/perl";
use Config::Simple;
use ZBH::SGE;

sub main ($ $ $) {

	my $starter = shift;
	my $graph   = shift;
	my $cluster = shift;

	return ("failure")
	  if ( !defined($graph)
		|| !defined($cluster)
		|| !ZBH::SGE::is_file_exists($graph) );

	return ("started")
	  if ( ZBH::SGE::is_background_process_sge($starter) );

	system("qsub -S /bin/bash -wd $FindBin::Bin $starter $graph $cluster");

	return ("wait");
}

exit( print( main( "$FindBin::Bin/bin/clustering.sh", $ARGV[0], $ARGV[1] ) ) );
